# Generated by Django 2.2.12 on 2020-07-18 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('restaurants', '0002_auto_20200713_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Waiting'), (2, 'On the Way'), (3, 'Delivered'), (4, 'Failed')])),
                ('price', models.IntegerField()),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Client')),
                ('deliveryman', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='users.DeliveryMan')),
                ('item', models.ManyToManyField(related_name='item_order', to='restaurants.Item')),
            ],
        ),
    ]
