# Generated by Django 2.2.12 on 2020-07-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_review',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
