# Generated by Django 2.2.12 on 2020-07-18 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20200718_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_review',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.DeliveryMan'),
        ),
    ]
