# Generated by Django 2.2.12 on 2020-06-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20200611_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='available_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='available_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
