# Generated by Django 2.2.12 on 2020-07-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20200718_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Waiting Deliveryman'), (2, 'On the Way'), (3, 'Delivered'), (4, 'Failed')]),
        ),
    ]
