# Generated by Django 2.2.12 on 2020-07-18 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20200718_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.DeliveryMan'),
        ),
    ]
