# Generated by Django 2.2.12 on 2020-07-18 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20200718_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client_review',
        ),
    ]
