# Generated by Django 2.2.12 on 2020-07-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_remove_order_client_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Waiting for Deliveryman'), (2, 'On the Way'), (3, 'Delivered'), (4, 'Failed')]),
        ),
    ]
