# Generated by Django 2.2.12 on 2020-05-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200507_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
