# Generated by Django 2.2.12 on 2020-05-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200525_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantadmin',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
