# Generated by Django 2.2.12 on 2020-05-26 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200526_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_verified',
        ),
    ]
