# Generated by Django 2.2.12 on 2020-06-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20200611_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(default='Special', max_length=30),
            preserve_default=False,
        ),
    ]
